version: '3.9'

services:
  db:
    image: postgres:16
    container_name: teamtasks-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: teamtasks
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./src/dB/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  backend:
    build:
      context: ./src/back_end
    container_name: teamtasks-backend
    restart: unless-stopped
    environment:
      DATABASEURL: postgres://admin:admin@db:5432/teamtasks
    depends_on:
      - db

  frontend:
    build:
      context: ./src/front_end
    container_name: teamtasks-frontend
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  db-data: